<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    /* Recherche Maps */

    public function getObservationByCriteria($criteria){
        // Création de l'alias
        $qb = $this->createQueryBuilder('o');

        $qb->where('o.species = :criteria')->setParameter('criteria', $criteria);

        return $qb->getQuery()->getResult();
    }

    /* Statistiques du dashboard */

    public function getValidatedObservationsByUser($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->andWhere('o.observer = :user')
            ->setParameters(array(
                'validate' => 1,
                'user' => $user));

        return $qb
            ->getQuery()
            ->getResult();
    }
    

    public function getRefusedObservationsByUser($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->andWhere('o.observer = :user')
            ->setParameters(array(
                'validate' => 0,
                'user' => $user));
        
        return $qb
            ->getQuery()
            ->getResult();
        
    } public function getValidatedObservationsByValidator($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->andWhere('o.validator = :user')
            ->setParameters(array(
                'validate' => 1,
                'user' => $user));
        
        return $qb
            ->getQuery()
            ->getResult();
    }
    
     public function getRefusedObservationsByValidator($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->andWhere('o.validator = :user')
            ->setParameters(array(
                'validate' => 0,
                'user' => $user));
        
        return $qb
            ->getQuery()
            ->getResult();
    }
    
}
