<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserValidatedObservations()
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->setParameter('validate', 1);
        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getUserRefusedObservations()
    {
        $qb = $this->createQueryBuilder('o')
            ->where('o.validate = :validate')
            ->setParameter('validate', 0);
        return $qb
            ->getQuery()
            ->getResult();
    }
}
