<?php

namespace AppBundle\Repository;

/**
 * SpeciesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
