<?php

namespace AppBundle\Repository;

/**
 * SpeciesFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
